In [536]:
import numpy as np
from numpy import genfromtxt

In [537]:
data = genfromtxt("../DATA/bank_note_data.txt", delimiter=",")
data


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [538]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [539]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [540]:
X = features
y = labels


In [541]:
from sklearn.model_selection import train_test_split


In [542]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [543]:
# 66%
len(X_train)

919

In [544]:
# 33%
len(X_test)

453

In [545]:
from sklearn.preprocessing import MinMaxScaler



In [546]:
scaler = MinMaxScaler()

In [547]:
scaler.fit(X_train)

MinMaxScaler()

In [548]:
scaled_x_train = scaler.transform(X_train)
scaled_x_test = scaler.transform(X_test)

In [549]:
scaled_x_train.max()

np.float64(1.0000000000000002)

In [550]:
X_train.max()

np.float64(17.9274)

In [551]:
from keras.models import Sequential
from keras.layers import Dense


In [552]:
# 11.40 minutes
model = Sequential()
model.add(Dense(4, input_dim=4, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

/Users/danieltuttle/projects/opencv-practice/venv/lib/python3.9/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [553]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [554]:
model.fit(scaled_x_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 0s - 10ms/step - accuracy: 0.5680 - loss: 0.6574
Epoch 2/50
29/29 - 0s - 1ms/step - accuracy: 0.5843 - loss: 0.6530
Epoch 3/50
29/29 - 0s - 1ms/step - accuracy: 0.5974 - loss: 0.6484
Epoch 4/50
29/29 - 0s - 924us/step - accuracy: 0.6083 - loss: 0.6435
Epoch 5/50
29/29 - 0s - 845us/step - accuracy: 0.6159 - loss: 0.6382
Epoch 6/50
29/29 - 0s - 911us/step - accuracy: 0.6213 - loss: 0.6328
Epoch 7/50
29/29 - 0s - 867us/step - accuracy: 0.6289 - loss: 0.6271
Epoch 8/50
29/29 - 0s - 873us/step - accuracy: 0.6376 - loss: 0.6212
Epoch 9/50
29/29 - 0s - 891us/step - accuracy: 0.6420 - loss: 0.6154
Epoch 10/50
29/29 - 0s - 917us/step - accuracy: 0.6453 - loss: 0.6090
Epoch 11/50
29/29 - 0s - 841us/step - accuracy: 0.6583 - loss: 0.6025
Epoch 12/50
29/29 - 0s - 832us/step - accuracy: 0.6714 - loss: 0.5959
Epoch 13/50
29/29 - 0s - 846us/step - accuracy: 0.6768 - loss: 0.5893
Epoch 14/50
29/29 - 0s - 807us/step - accuracy: 0.6812 - loss: 0.5824
Epoch 15/50
29/29 - 0s - 833us/ste

In [555]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
predictions = model.predict(scaled_x_test)
predicted_classes = (predictions > 0.5).astype("int32")
predicted_classes


15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [556]:
confusion_matrix(y_test, predicted_classes)

array([[243,  14],
       [ 45, 151]])

In [557]:
print(classification_report(y_test, predicted_classes))

              precision    recall  f1-score   support

         0.0       0.84      0.95      0.89       257
         1.0       0.92      0.77      0.84       196

    accuracy                           0.87       453
   macro avg       0.88      0.86      0.86       453
weighted avg       0.87      0.87      0.87       453


In [558]:
model.save("mysupermodel.h5")

In [559]:
from keras.models import load_model

In [560]:
loaded = load_model("mysupermodel.h5")

In [561]:
loaded.predict(scaled_x_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


array([[0.15191083],
       [0.3562829 ],
       [0.3246268 ],
       [0.4484964 ],
       [0.0758694 ],
       [0.05440471],
       [0.2691343 ],
       [0.02208472],
       [0.06017398],
       [0.21030642],
       [0.24573752],
       [0.552357  ],
       [0.38140768],
       [0.74421847],
       [0.66845846],
       [0.1964299 ],
       [0.73309004],
       [0.74070275],
       [0.8767154 ],
       [0.7205379 ],
       [0.07392768],
       [0.16533768],
       [0.6645544 ],
       [0.03847809],
       [0.874354  ],
       [0.04002591],
       [0.05623325],
       [0.7596229 ],
       [0.00917419],
       [0.01464746],
       [0.52723074],
       [0.19742975],
       [0.25049856],
       [0.87925094],
       [0.87094146],
       [0.03597932],
       [0.2313989 ],
       [0.45920348],
       [0.605193  ],
       [0.17896749],
       [0.22899851],
       [0.55506074],
       [0.4832379 ],
       [0.08261457],
       [0.8485258 ],
       [0.864382  ],
       [0.7537704 ],
       [0.108

In [562]:
# model.metrics_names