In [144]:
# https://www.udemy.com/course/python-for-computer-vision-with-opencv-and-deep-learning/learn/lecture/12257482#overview
import numpy as np

In [145]:
mylist = [1, 2, 3]
type(mylist)

list

In [146]:
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [147]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [148]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [149]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [150]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
arr


array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [151]:
np.random.seed(101)
arr2 = np.random.randint(0, 100, 10)
arr2

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [152]:
x = arr.min()
x


np.int64(9)

In [153]:
x = arr.mean()
x

np.float64(60.8)

In [154]:
x = arr.max()
x

np.int64(95)

In [155]:
arr.reshape(5, 2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [156]:
mat = np.arange(0, 100)
mat = mat.reshape(10,10)

mat[0, 1]
mat[:, 1]


array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])